FinalProj/FinalProj/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FinalProj.Models
{
    public class User
    {
        public User()
        {
            Adverts = new HashSet<Advert>();
        }

        public int Id { get; set; }

        [Required(ErrorMessage = "Adı  daxil edin")]
        [StringLength(50, ErrorMessage = "Duzgun Ad daxil edin!")]
        [MinLength(3, ErrorMessage = "Adi daxil edin!")]
        public string Firstname { get; set; }

        [DataType(DataType.Text, ErrorMessage = "Duzgun Soyad daxil edin!")]
        [Required(ErrorMessage = "Soyadı daxil edin")]
        [StringLength(50, ErrorMessage = "Duzgun Soyad daxil edin!")]
        [MinLength(3, ErrorMessage = "Soyadı daxil edin!")]
        public string Lastname { get; set; }

        [DataType(DataType.PhoneNumber, ErrorMessage = "Telefon nomresini daxil edin")]
        [Required(ErrorMessage = "Telefon nomresini daxil edin")]
        [StringLength(13, ErrorMessage = "Duzgun nömre daxil edin")]
        [MinLength(10, ErrorMessage = "Duzgun nomre daxil edin")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Email daxil edin")]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", ErrorMessage = "Duzgun Email Daxil Edin!")]
        [Index("UN_Email", IsUnique = true)]
        [DataType(DataType.EmailAddress)]
        [StringLength(50, ErrorMessage = "Duzgun Email daxil edin")]
        [MinLength(5, ErrorMessage = "Duzgun Email daxil edin")]
        public string Email { get; set; }

        [MinLength(8, ErrorMessage = "Parol qisadir!")]
        [StringLength(300,ErrorMessage ="Parol Maksimum 300 sinvol ola biler")]
        [Required(ErrorMessage = "Parolu Daxil Edin")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Təkrar Parolu daxil edin")]
        [Compare(nameof(Password))]
        [StringLength(300)]
        public string ConfirmPassword { get; set; }
        public bool Status { get; set; }

        public virtual ICollection<Advert> Adverts { get; set; }


    }
}

FinalProj/FinalProj/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FinalProj.Data;

namespace FinalProj.Areas.Admin.Controllers
{[isAdmin]
    public class UsersController : Controller
    {
        readonly FinalProjContext _context;
        public UsersController()
        {
            _context = new FinalProjContext();
        }
        // GET: Admin/Users
        public ActionResult Index()
        {
            return View(_context.Users.ToList());
        }

        public ActionResult useradv (int id)
        {
            return View(_context.Adverts.Where(m=>m.UserId == id).ToList());
        }
    }
}

FinalProj/FinalProj/Controllers/AdvertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FinalProj.Models;
using FinalProj.ViewModels;
using FinalProj.Data;
using static FinalProj.FileExtensions.FileExtensions;
using System.Threading.Tasks;
using System.Data.Entity;

namespace FinalProj.Controllers
{
    [Authorization]
    public class AdvertController : Controller
    {
        FinalProjContext _context;
        public AdvertController()
        {
            _context = new FinalProjContext();
        }

        // GET: Advert
        [AllowAnonymous]
        public ActionResult Detail(int? id)
        {
            if (id == null) return HttpNotFound();

            var dbadvert = _context.Adverts.Find(id);

            if (dbadvert == null) return HttpNotFound();

            forDetail vm = new forDetail()
            {
                adverts = _context.Adverts.Where(m => m.User.Status == false && m.CityId == dbadvert.CityId && m.Id != dbadvert.Id).OrderByDescending(m => m.IsVip == true).ThenBy(m => m.CreatedAt).ToList(),
                dbadvert = dbadvert
            };


            return View(vm);
        }


        public ActionResult Create()
        {
            ViewBag.Cities = _context.Cities.ToList();
            ViewBag.RentType = _context.RentTypes.ToList();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task <ActionResult>Create([Bind(Include = "Price,RoomCount,BedRoom,BathRoom,RoomArea,CreatedAt,Description,IsVip,IsNew,Photo,RentTypeId,UserId,CityId,Address")]Advert advert)
        {
            ViewBag.Cities = _context.Cities.ToList();
            ViewBag.RentType = _context.RentTypes.ToList();
            var CurrentUser = Session["lguser"] as FinalProj.Models.User;
            if (!ModelState.IsValid) return View(advert);

            if (advert.Photo == null)
            {
                ModelState.AddModelError("Photo", "Şəkli Daxil Edin!");
                return View(advert);
            }

            if (!advert.Photo.IsImage())
            {
                ModelState.AddModelError("Photo", "Şəkli Daxil Edin!");
                return View(advert);
            }

            advert.Image = advert.Photo.SaveImage("homes");
            advert.CreatedAt = DateTime.Now;
            advert.UserId = CurrentUser.Id;
            _context.Adverts.Add(advert);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index","User");
        }

        public ActionResult Edit(int? id)
        {
            ViewBag.Cities = _context.Cities.ToList();
            ViewBag.RentType = _context.RentTypes.ToList();

            if (id == null) return HttpNotFound();

            var editadv = _context.Adverts.Find(id);
            var dbuser = Session["lguser"] as User;

            if (editadv == null) return HttpNotFound();

            if (editadv.UserId != dbuser.Id) return HttpNotFound();

            return View(editadv);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,UserId,Image,CreatedAt,Price,RoomCount,BedRoom,BathRoom,RoomArea,CreatedAt,Description,IsVip,IsNew,Photo,RentTypeId,UserId,CityId,Address")]Advert advert)
        {
            ViewBag.Cities = _context.Cities.ToList();
            ViewBag.RentType = _context.RentTypes.ToList();
            
            if (!ModelState.IsValid) return View(advert);

            if (advert.Photo != null)
            {
               if(!advert.Photo.IsImage())
                {
                    ModelState.AddModelError("Photo", "Şəkli Daxil Edin!");
                    return View(advert);
                }
                DeleteImage("~/Images", advert.Image);
                advert.Image=advert.Photo.SaveImage("homes");
            }

            _context.Entry(advert).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            

            return RedirectToAction("Index","User");
        }
        [AllowAnonymous]
        public ActionResult Sale()
        {
            ViewBag.TotalSaleCount = _context.Adverts.Where(m => m.RentTypeId == 1 && m.User.Status == false).Count();
            var dbsaled = _context.Adverts.Where(m => m.RentTypeId == 1 && m.User.Status==false).OrderByDescending(m => m.CreatedAt).Take(6).ToList();
            return View(dbsaled);
        }
        [AllowAnonymous]
        public ActionResult Rent()
        {
            ViewBag.TotalRentCount = _context.Adverts.Where(m => m.RentTypeId == 2 && m.User.Status == false).Count();
            var dbrented = _context.Adverts.Where(m => m.RentTypeId == 2 && m.User.Status == false).OrderByDescending(m => m.CreatedAt).Take(6).ToList();
            return View(dbrented);
        }
    }
}

FinalProj/FinalProj/Controllers/UserController.cs
using FinalProj.Data;
using FinalProj.Models;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Helpers;
using System.Web.Mvc;

namespace FinalProj.Controllers
{
    [Authorization]
    public class UserController : Controller
    {
        FinalProjContext _context;
        public UserController()
        {
            _context = new FinalProjContext();
        }
        public ActionResult Index()
        {
            User user = Session["lguser"] as User;

            ViewBag.UserId = user.Id;
            ViewBag.TotalCount = _context.Adverts.Where(m => m.UserId == user.Id).Count();

            return View(_context.Adverts.Where(m => m.UserId == user.Id && m.User.Status == false).OrderByDescending(m => m.CreatedAt).Take(3).ToList());
        }


        public ActionResult Detail(int? id)
        {
            if (id == null) return HttpNotFound();
            var realuser = Session["lguser"] as User;
            var useradv = _context.Adverts.Find(id);
            if (useradv == null) return HttpNotFound();
            if (useradv.UserId != realuser.Id) return HttpNotFound();

            return View(useradv);
        }

        public ActionResult Privacy(int? id)
        {
            if (id == null) return HttpNotFound();

            var edituser = _context.Users.Find(id);

            if (edituser == null) return HttpNotFound();

            if (Session["lguser"] == null) return HttpNotFound();

            if (Session["lguser"] != null)
            {
                var user = Session["lguser"] as FinalProj.Models.User;
                if (id != user.Id) return HttpNotFound();

            }

            return View(edituser);
        }

        [HttpPost]
        public async Task<ActionResult> Privacy(string oldpass, string newpass, string confpass, string accblock)
        {
            if (oldpass != null && newpass != null && confpass != null && accblock != null) return HttpNotFound();

            var dbuser = Session["lguser"] as FinalProj.Models.User;
            var mainuser = _context.Users.Find(dbuser.Id);

            if (oldpass != null && newpass != null && confpass != null)
            {
                if (!Crypto.VerifyHashedPassword(dbuser.Password, oldpass))
                {
                    return Json(new { statuscode = "400", errormessage = "Kohnə parol duzgun deyil" }, JsonRequestBehavior.AllowGet);
                }

                if (newpass.Trim().Length <= 7)
                {
                    return Json(new { statuscode = "400", errormessage = "Parol ən az 8 sinvol olmalıdır!" }, JsonRequestBehavior.AllowGet);
                }
                if (newpass.Trim() != confpass.Trim())
                {
                    return Json(new { statuscode = "400", errormessage = "Yeni parolla təsdiq parolu uyğun deyil" }, JsonRequestBehavior.AllowGet);
                }

                mainuser.ConfirmPassword = mainuser.Password = Crypto.HashPassword(newpass);
                await _context.SaveChangesAsync();
                dbuser.ConfirmPassword = dbuser.Password = mainuser.Password;
                return Json(new { statuscode = "200", data = Url.Action("Index", "Home") }, JsonRequestBehavior.AllowGet);
            }

            if (oldpass != null || newpass != null || confpass != null) return HttpNotFound();

            if (accblock == null)
            {
                return Json(new { statuscode = "400", errormessage = "Parolu daxil edin!" }, JsonRequestBehavior.AllowGet);
            }

            if (!Crypto.VerifyHashedPassword(mainuser.Password, accblock))
            {
                return Json(new { statuscode = "400", errormessage = "Parolu Düzgün Deyil!" }, JsonRequestBehavior.AllowGet);
            }

            mainuser.Status = true;
            await _context.SaveChangesAsync();
            Session.Clear();

            return Json(new { statuscode = "200", data = Url.Action("Index", "Home") }, JsonRequestBehavior.AllowGet);


        }

        public ActionResult Liked(int id)
        {
            var dbliked = _context.Likes.Where(m => m.UserId == id).Select(m => m.AdvertId).ToList();
            var useradv = _context.Adverts.Where(m => m.User.Status == false && dbliked.Contains(m.Id)).ToList();
            return View(useradv);
        }
    }
}

FinalProj/FinalProj/Views/User/Detail.cshtml
@model FinalProj.Models.Advert
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="homedetail">
    <div class="homedetail my-5">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="wrapper">
                        <img src="~/Images/@Model.Image" alt="">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="overview">
                        <div class="modbuttons">
                            <a href="@Url.Action("Edit","Advert",new { id = Model.Id })"><i class="btn btn-warning fas fa-edit"></i></a>
                            <a href="#" data-toggle="modal" data-target="#exampleModalCenter"><i class="btn btn-danger  fas fa-trash"></i></a>
                            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLongTitle">  <span style="color:red">@Model.City.CityName</span> şəhərindən olan elanı silmək istəyirsiniz?</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            "Bu elanı silsəniz bir daha bərpa edə bilməyəcəksiniz"
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-success" data-dismiss="modal">Imtina</button>
                                            <button type="button" id="deladv" data-id="@Model.Id" class="btn btn-danger">Sil</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <h4>
                            Ümumi Melumat
                            <hr>
                        </h4>

                        <div class="d-flex">
                            <p class="first-p">Qiyməti:</p>
                            <p class="second-p">@Model.Price <SUP>₼</SUP> </p>
                        </div>
                        <div class="d-flex">
                            <p class="first-p">Yataq Otağı:</p>
                            <p class="second-p">@Model.BedRoom</p>
                        </div>
                        <div class="d-flex">
                            <p class="first-p">Hamam Otağı:</p>
                            <p class="second-p">@Model.BathRoom</p>
                        </div>
                        <div class="d-flex">
                            <p class="first-p">Sahəsi:</p>
                            <p class="second-p">@Model.RoomArea m <sup>2</sup></p>
                        </div>
                        <div class="d-flex">
                            <p class="first-p">Növü:</p>
                            <p class="second-p">@Model.RentType.SaleType</p>
                        </div>
                        <div class="d-flex">
                            <p class="first-p">Adresi:</p>
                            <p class="second-p">@Model.City.CityName,@Model.Address </p>
                        </div>

                    </div>
                    <div class="description">
                        <h4>
                            Haqqında Melumat
                            <hr>
                        </h4>
                        <p class="descrip">
                            @Model.Description
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script>
        $(function () {
            $(document).on("click", "#deladv", function () {
               var delid = $("#deladv").attr("data-id")
                $.ajax({
                    url: "/AJAX/DeleteAdvert",
                    data: { deleteid: delid },
                    type:"GET",
                    success: function (res) {
                        if (res.status === "400") {
                            swal({
                                title: "Xəta",
                                text: "Elanı silmə uğursuz oldu.Düzgün məlumat daxil etdiyinizdən əmin olun!",
                                icon: "error",
                                button: "Ok",
                            });
                        } else {
                            swal("Uğurlu", "Elan Uğurla silindi", "success")
                                .then(willRedirect => {
                                    if (willRedirect) {
                                        window.location.href = res.data;
                                    }
                                })
                        }
                    }
                })

            })
        })

    </script>
}

FinalProj/FinalProj/Views/User/Index.cshtml
@model List<FinalProj.Models.Advert>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="userpage">
    <div class="userpage">
        <div class="container">
            <div id="forappend" class="row">
                @foreach (var item in Model)
                {
                    <div class="foritem col-md-4">
                       <div class="card item">
                            <a href="@Url.Action("Detail","User",new { id = item.Id })">
                                <div class="card">
                                    <div class="forimage">
                                        <img src="~/Images/@item.Image" class="card-img-top"
                                             alt="...">
                                    </div>
                                    @{
                                        if (item.IsNew == true)
                                        {
                                            <div class="new">
                                                <h4>Yeni</h4>
                                            </div>
                                        }
                                        if (item.IsVip)
                                        {
                                            <div class="vip">
                                                <span><i class="fas fa-crown"></i></span>
                                            </div>
                                        }
                                    }

                                    <div class="card-body">
                                        
                                        <h5 class="card-title">₼ @item.Price</h5>
                                        <div class="icons">
                                            <i class="fas fa-bed"></i> <span>@item.BedRoom y.o</span>
                                            <i class="fas fa-bath"></i> <span>@item.BathRoom h.o</span>
                                            <i class="fas fa-ruler-horizontal"></i> <span>@item.RoomArea m<sup>2</sup></span>
                                        </div>
                                        <p>@item.Address</p>
                                        <p>@item.City.CityName</p>
                                        <p class="text-warning text-center bg-info">@item.RentType.SaleType</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                }

            </div>
        </div>
        @{
            if (ViewBag.TotalCount > 3)
            {
                <input type="button" style="display:block;margin:20px auto;cursor:pointer;" id="loadmore" class="btn btn-warning " value="Daha Çox" />
            }
            if (Model.Count == 0)
            {
                <div class="container">
                    <h3>Siz Heç Bir Elan Yerləşdirməmisiniz. </h3>
                </div>

            }
        }
    </div>
</section>



@section scripts{
    <script>
        $(function () {
            var pagedata = 0;
            var userid = @ViewBag.UserId;
            var totalcount = @ViewBag.TotalCount;
            $(document).on("click", "#loadmore", function () {
                pagedata += 3;

                $.ajax({
                    url: "/AJAX/LoadMore",
                    type: "GET",
                    data: { page: pagedata , userid:userid },
                    success: function (res) {
                        $("#forappend").append(res)
                        if (pagedata + 3 >= totalcount) {
                            $("#loadmore").remove();
                        }

                    }
                })
            })

        })
    </script>

}

FinalProj/FinalProj/Views/User/Liked.cshtml
@model List<FinalProj.Models.Advert>

@{
    ViewBag.Title = "Liked";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="userpage">
    <div class="userpage">
        <div class="container">
            <div id="forappend" class="row">
                @foreach (var item in Model)
                {
                    <div class="foritem col-md-4">
                        <div class="card item">
                            <a href="@Url.Action("Detail","Advert",new { id = item.Id })">
                                <div class="card">
                                    <div class="forimage">
                                        <img src="~/Images/@item.Image" class="card-img-top"
                                             alt="...">
                                    </div>
                                    @{
                                        if (item.IsNew == true)
                                        {
                                            <div class="new">
                                                <h4>Yeni</h4>
                                            </div>
                                        }
                                        if (item.IsVip)
                                        {
                                            <div class="vip">
                                                <span><i class="fas fa-crown"></i></span>
                                            </div>
                                        }
                                    }

                                    <div class="card-body">
                                        <div class="liked">
                                            <span><i data-id="@item.Id" class="fas fa-thumbs-down"></i></span>
                                        </div>
                                        <h5 class="card-title">₼ @item.Price</h5>
                                        <div class="icons">
                                            <i class="fas fa-bed"></i> <span>@item.BedRoom y.o</span>
                                            <i class="fas fa-bath"></i> <span>@item.BathRoom h.o</span>
                                            <i class="fas fa-ruler-horizontal"></i> <span>@item.RoomArea m<sup>2</sup></span>
                                        </div>
                                        <p>@item.Address</p>
                                        <p>@item.City.CityName</p>
                                        <p class="text-warning text-center bg-info">@item.RentType.SaleType</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>